pipeline {
    agent any
    tools {
      maven "maven-1.0"
    }
    stages {
        stage('Build') {
            steps {
                dir('jenkins/ejercicios/cicd/infra-ii') {
                    sh 'mvn -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('jenkins/ejercicios/cicd/infra-ii') {
                    sh 'mvn test'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    post {
        success {
            dir (‘maven-adderapp’) {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }
    }
}
