pipeline {
    agent any
    tools {
      maven "maven-nodo-principal"
    }
    stages {
        stage('Build') {
            steps {
                dir('jenkins/ejercicios/maven-adderapp') {
                    sh 'mvn -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('jenkins/ejercicios/maven-adderapp') {
                    sh 'mvn test'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    post {
       always {
           dir('jenkins/ejercicios/maven-adderapp') {
               junit 'target/surefire-reports/*.xml'
           }
       }
       success {
           dir('jenkins/ejercicios/maven-adderapp') {
             archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
           }
       }
    }
}
